### ISSUE TITLE
顔認証処理をgpuを利用して動作するように対応する

### ISSUE THREAD

**Issue by sakamomo554101** [kurama554101/sample_trtis#14]

**Comment by sakamomo554101** [comment]
http://dlib.net/faq.html#top

上記見ると、cudaを有効にできそう。
dlib.DLIB_USE_CUDAをTrueにすればよいのかな。

**Comment by sakamomo554101** [comment]
https://github.com/davisking/dlib/blob/870f49a63610858e4884d746334461f7887f4410/dlib/CMakeLists.txt

dlibのCMakeListsを真面目に読まないとかなぁ・・

**Comment by sakamomo554101** [comment]
https://stackoverflow.com/questions/51697468/how-to-check-if-dlib-is-using-gpu-or-not

CMAKE時にオプション指定すれば良さそう？

**Comment by sakamomo554101** [comment]
https://qiita.com/SousukeShimoyama/items/a6b853a1575623f603cf

CUDA環境があれば、自動的にcudaをONにしてくれる？
※CMakeListsのFindCUDAって、そういうこと？

**Comment by aShotaSakamoto** [comment]
あれぇ、、docker-composeでruntime指定ができん・・。バージョンは1.24なんだが。

<pre>
docker-compose version 1.24.0, build 0aa5906
Docker version 18.09.6, build 481bc77
</pre>

**Comment by sakamomo554101** [comment]
docker-compose.ymlのバージョン指定が重要。
3.x系ではruntime指定は出来ない。2.3や2.4を指定する必要がある。

**Comment by sakamomo554101** [comment]
p2.xlargeではTesla K80のGPUのため、TRTISは動作しない。
そこで、g4dn.xlarge（T4系）を利用するようにする。

**Comment by sakamomo554101** [comment]
速度差がGPUとCPUでは、dlib処理のみで5倍程度異なっていた。

**Comment by sakamomo554101** [comment]
あとは、、GPUでビルドするか・CPUでビルドするか、を場合分けできるように色々と直す必要がある。

**Comment by sakamomo554101** [comment]
#19 で対応した。
