### ISSUE TITLE
顔認証処理でバッチ対応を行う

### ISSUE THREAD

**Issue by aShotaSakamoto** [kurama554101/sample_trtis#16]

**Comment by sakamomo554101** [comment]
https://github.com/NVIDIA/tensorrt-inference-server/blob/75268ffc031f009983b9e12c6e62d1dabd08f79e/src/core/sequence_batch_scheduler.cc#L385-L392

SequentialBatcherだと、バッチサイズ1で固定っぽい。
ということで、ステートフルなモデルだとバッチサイズ1以外は使えない（将来的なTRTISでは対応される可能性はある）
